name: GitHub Action Lint
description: Lints GitHub Actions
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can create/delete comments. Usually - 'secrets.GITHUB_TOKEN'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Run npm ci if needed
      if: hashFiles('package-lock.json') != ''
      shell: bash
      run: npm ci
    - name: Install actionlint
      uses: KeisukeYamashita/setup-release@v1.0.2
      with:
        repository: rhysd/actionlint
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
    - name: Check build
      uses: open-turo/actions-gha/check-build@v1
      if: hashFiles('package-lock.json') != ''
      with:
        github-token: ${{ inputs.github-token }}
