name: GitHub Action Lint
description: GitHub Action that runs lint on a GitHub Action
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can create/delete comments. Usually - 'secrets.GITHUB_TOKEN'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - name: Run npm ci if needed
      if: hashFiles('package-lock.json') != ''
      shell: bash
      run: npm ci
    - name: Install actionlint via bash
      shell: bash
      run: |
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        actionLintVersion=`./actionlint -version | sed -n 1p`
        destDir="/opt/hostedtoolcache/release/$actionLintVersion"
        mkdir -p "$destDir"
        mv actionlint "$destDir"
        echo "$destDir" >> "$GITHUB_PATH"
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v1
    - name: Check build
      uses: open-turo/actions-gha/check-build@v1
      if: hashFiles('package-lock.json') != ''
      with:
        github-token: ${{ inputs.github-token }}
