name: "GitHub Action Lint"
description: "Lints GitHub Actions"
runs:
  using: composite
  steps:
    - uses: wagoid/commitlint-github-action@v4
      with:
        configFile: .commitlintrc.yml
    - name: Run npm ci if needed
      shell: bash
      run: |
        if [ -f package-lock.json ]; then
          npm ci
        fi
    - uses: KeisukeYamashita/setup-release@v1.0.2
      with:
        repository: rhysd/actionlint
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
