name: GitHub Action Lint
description: GitHub Action that runs lint on a GitHub Action
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  github-token:
    required: true
    description: GitHub token that can create/delete comments. Usually - 'secrets.GITHUB_TOKEN'
  node-version:
    required: false
    description: Node version to use
    default: "18"
  semantic-release-extra-plugins:
    required: false
    description: Extra plugins for pre-install when linting the release notes. You can also specify specifying version range for the extra plugins if you prefer.  Defaults to install @open-turo/semantic-release-config.
    default: |
      @open-turo/semantic-release-config
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Run npm ci if needed
      if: hashFiles('package-lock.json') != ''
      shell: bash
      run: npm ci
    - name: Install actionlint
      uses: open-turo/action-install-release@v1
      with:
        repository: rhysd/actionlint
    - name: Pre-commit
      uses: open-turo/action-pre-commit@v3
    - name: Check build
      uses: open-turo/actions-gha/check-build@v2
      if: hashFiles('package-lock.json') != ''
      with:
        github-token: ${{ inputs.github-token }}
    - name: Check release notes on pull_request
      if: github.event_name == 'pull_request'
      uses: open-turo/actions-release/lint-release-notes@v4
      with:
        extra-plugins: ${{ inputs.semantic-release-extra-plugins }}
