name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: ./lint
        with:
          checkout-repo: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ./test
        with:
          checkout-repo: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  action-test:
    name: Test / Action
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ./release
        with:
          checkout-repo: true
          dry-run: true
