name: CI

on:
  pull_request: {}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint
        uses: ./lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          semantic-release-extra-plugins: |
            @open-turo/semantic-release-config

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./test
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  action-test:
    name: Test / Action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release
        uses: ./release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          checkout-repo: false
          dry-run: true
          extra-plugins: |
            @open-turo/semantic-release-config
