name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v2
        with:
          configFile: .commitlintrc.yml
      - name: Download actionlint
        id: get_actionlint
        shell: bash
        run: |
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          export LOCAL_BIN="$HOME/.local/bin"
          mkdir -p "$LOCAL_BIN"
          mv actionlint "$LOCAL_BIN"
          echo "$LOCAL_BIN" >> "$GITHUB_PATH"
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v4.1.9
  action-test:
    name: Action test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./release
        id: release
        with:
          dry-run: true
